# Starter pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
 buildConfiguration: 'Release'
 percorsoPreBuild: '../directoryPreBuild'
 percorsoPostBuild: '../DirectoryPostBuild'


pool:
  vmImage: windows-2019
  demands:
  - msbuild
  - visualstudio

#processo di prebuild
steps:
#installazione .NET
- task: UseDotNet@2
  displayName: Use .NET SDK 5.x
  inputs:
    version: 5.x

#installazione di Directx

#aggiunta VSBuild
- task: VSBuild@1
  inputs:
    solution: '**\*.sln' 
    vsVersion: 'latest'
    platform: 'x64'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'
    logProjectEvents: true
    createLogFile: false
    logFileVerbosity: 'diagnostic'

- task: DotNetCoreCLI@1
  displayName: Build the project - Release
  inputs:
    command: build
    arguments: --no-restore --configuration Release --output "$(percorsoPostBuild)"
    projects: '$(percorsoPreBuild)'

